config/routes.rb
Desafioprodec::Application.routes.draw do
  resources :ocorrencia

  resources :declarantes

  resources :enderecos

  get '/ocorrencia/new(.:format)' => 'ocorrencia#new'

  

end

app/models/declarante.rb
class Declarante < ActiveRecord::Base
	has_one :ocorrencia, :dependent => :destroy
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
	has_one :ocorrencia, :dependent => :destroy
end

app/models/ocorrencia.rb
class Ocorrencia < ActiveRecord::Base
  belongs_to :declarante
  belongs_to :endereco
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/declarantes_controller.rb
class DeclarantesController < ApplicationController
  before_action :set_declarante, only: [:show, :edit, :update, :destroy]

  # GET /declarantes
  # GET /declarantes.json
  def index
    @declarantes = Declarante.all
  end

  # GET /declarantes/1
  # GET /declarantes/1.json
  def show
  end

  # GET /declarantes/new
  def new
    @declarante = Declarante.new
  end

  # GET /declarantes/1/edit
  def edit
  end

  # POST /declarantes
  # POST /declarantes.json
  def create
    @declarante = Declarante.new(declarante_params)

    respond_to do |format|
      if @declarante.save
        format.html { redirect_to @declarante, notice: 'Declarante was successfully created.' }
        format.json { render action: 'show', status: :created, location: @declarante }
      else
        format.html { render action: 'new' }
        format.json { render json: @declarante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /declarantes/1
  # PATCH/PUT /declarantes/1.json
  def update
    respond_to do |format|
      if @declarante.update(declarante_params)
        format.html { redirect_to @declarante, notice: 'Declarante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @declarante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /declarantes/1
  # DELETE /declarantes/1.json
  def destroy
    @declarante.destroy
    respond_to do |format|
      format.html { redirect_to declarantes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_declarante
      @declarante = Declarante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def declarante_params
      params.require(:declarante).permit(:nome, :naturalidade, :email, :telefone)
    end
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render action: 'show', status: :created, location: @endereco }
      else
        format.html { render action: 'new' }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:logradouro, :numero, :complemento, :cep)
    end
end

app/controllers/ocorrencia_controller.rb
class OcorrenciaController < ApplicationController
  before_action :set_ocorrencium, only: [:show, :edit, :update, :destroy]

  # GET /ocorrencia
  # GET /ocorrencia.json
  def index
    @ocorrencia = Ocorrencia.all
  end

  # GET /ocorrencia/1
  # GET /ocorrencia/1.json
  def show
  end

  # GET /ocorrencia/new
  def new
    @ocorrencium = Ocorrencia.new
  end

  # GET /ocorrencia/1/edit
  def edit
  end

  # POST /ocorrencia
  # POST /ocorrencia.json
  def create
    @ocorrencium = Ocorrencia.new(ocorrencium_params)

    respond_to do |format|
      if @ocorrencium.save
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencia was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ocorrencium }
      else
        format.html { render action: 'new' }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocorrencia/1
  # PATCH/PUT /ocorrencia/1.json
  def update
    respond_to do |format|
      if @ocorrencium.update(ocorrencium_params)
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocorrencia/1
  # DELETE /ocorrencia/1.json
  def destroy
    @ocorrencium.destroy
    respond_to do |format|
      format.html { redirect_to ocorrencia_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ocorrencium
      @ocorrencium = Ocorrencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocorrencium_params
      params.require(:ocorrencium).permit(:data_ocorrencia, :declarante_id, :endereco_id, :detalhes, :tipo)
    end
end

app/controllers/ocorrencias_controller.rb
class OcorrenciasController < ApplicationController

	def index
		@ocorrencias = Ocorrencia.all
	end

	def create
		#@endereco = 
	end

	def new

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/declarante_helper.rb
module DeclaranteHelper
end

app/helpers/declarantes_helper.rb
module DeclarantesHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/ocorrencia_helper.rb
module OcorrenciaHelper
end

app/helpers/ocorrencias_helper.rb
module OcorrenciasHelper
end

app/views/declarantes/_form.html.erb
<%= form_for(@declarante) do |f| %>
  <% if @declarante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@declarante.errors.count, "error") %> prohibited this declarante from being saved:</h2>

      <ul>
      <% @declarante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :naturalidade %><br>
    <%= f.text_field :naturalidade %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/declarantes/edit.html.erb
<h1>Editing declarante</h1>

<%= render 'form' %>

<%= link_to 'Show', @declarante %> |
<%= link_to 'Back', declarantes_path %>

app/views/declarantes/index.html.erb
<h1>Listing declarantes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Naturalidade</th>
      <th>Email</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @declarantes.each do |declarante| %>
      <tr>
        <td><%= declarante.nome %></td>
        <td><%= declarante.naturalidade %></td>
        <td><%= declarante.email %></td>
        <td><%= declarante.telefone %></td>
        <td><%= link_to 'Show', declarante %></td>
        <td><%= link_to 'Edit', edit_declarante_path(declarante) %></td>
        <td><%= link_to 'Destroy', declarante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Declarante', new_declarante_path %>

app/views/declarantes/new.html.erb
<h1>New declarante</h1>

<%= render 'form' %>

<%= link_to 'Back', declarantes_path %>

app/views/declarantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @declarante.nome %>
</p>

<p>
  <strong>Naturalidade:</strong>
  <%= @declarante.naturalidade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @declarante.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @declarante.telefone %>
</p>

<%= link_to 'Edit', edit_declarante_path(@declarante) %> |
<%= link_to 'Back', declarantes_path %>

app/views/enderecos/_form.html.erb
<%= form_for(@endereco) do |f| %>
  <% if @endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% @endereco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logradouro %><br>
    <%= f.text_field :logradouro %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :complemento %><br>
    <%= f.text_field :complemento %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing endereco</h1>

<%= render 'form' %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<h1>Listing enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Logradouro</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Cep</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.logradouro %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.complemento %></td>
        <td><%= endereco.cep %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New endereco</h1>

<%= render 'form' %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logradouro:</strong>
  <%= @endereco.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @endereco.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @endereco.complemento %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @endereco.cep %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desafioprodec</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ocorrencia/_form.html.erb
<%= form_for(@ocorrencium) do |f| %>
  <% if @ocorrencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ocorrencium.errors.count, "error") %> prohibited this ocorrencium from being saved:</h2>

      <ul>
      <% @ocorrencium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_ocorrencia %><br>
    <%= f.datetime_select :data_ocorrencia %>
  </div>
  <div class="field">
    <%= f.label :declarante %><br>
    <%= f.text_field :declarante %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :detalhes %><br>
    <%= f.text_field :detalhes %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ocorrencia/edit.html.erb
<h1>Editing ocorrencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @ocorrencium %> |
<%= link_to 'Back', ocorrencia_index_path %>

app/views/ocorrencia/index.html.erb
<h1>Listing ocorrencia</h1>

<table>
  <thead>
    <tr>
      <th>Data ocorrencia</th>
      <th>Declarante</th>
      <th>Endereco</th>
      <th>Detalhes</th>
      <th>Tipo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ocorrencia.each do |ocorrencium| %>
      <tr>
        <td><%= ocorrencium.data_ocorrencia %></td>
        <td><%= ocorrencium.declarante %></td>
        <td><%= ocorrencium.endereco %></td>
        <td><%= ocorrencium.detalhes %></td>
        <td><%= ocorrencium.tipo %></td>
        <td><%= link_to 'Show', ocorrencium %></td>
        <td><%= link_to 'Edit', edit_ocorrencium_path(ocorrencium) %></td>
        <td><%= link_to 'Destroy', ocorrencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ocorrencia', new_ocorrencium_path %>

app/views/ocorrencia/new.html.erb
<h1>New ocorrencium</h1>

<%= render 'form' %>

<%= link_to 'Back', ocorrencia_index_path %>

app/views/ocorrencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data ocorrencia:</strong>
  <%= @ocorrencium.data_ocorrencia %>
</p>

<p>
  <strong>Declarante:</strong>
  <%= @ocorrencium.declarante %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @ocorrencium.endereco %>
</p>

<p>
  <strong>Detalhes:</strong>
  <%= @ocorrencium.detalhes %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @ocorrencium.tipo %>
</p>

<%= link_to 'Edit', edit_ocorrencium_path(@ocorrencium) %> |
<%= link_to 'Back', ocorrencia_index_path %>

app/views/ocorrencias/new.html.erb
<h1>Nova Ocorrência</h1>
<%= form_for :ocorrencia, url: ocorrencias_path do |f| %>
	<p>
		<%= f.label :tipo %><br/>
		<%= f.text_field :tipo %><br/>
	</p>

	<p>
		<%= f.label :data_ocorrencia %><br/>
		<%= f.text_field :data_ocorrencia %><br/>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>